Update：为susfs_def.h检查构建
Added checks for 'susfs_def.h' and updated base.c with conditional include.

diff --git a/.github/workflows/Build_Lenovo_ReSukiSU.yml b/.github/workflows/Build_Lenovo_ReSukiSU.yml
--- a/.github/workflows/Build_Lenovo_ReSukiSU.yml
+++ b/.github/workflows/Build_Lenovo_ReSukiSU.yml
@@ -225,6 +225,21 @@ jobs:
           cd ./common
           wget https://gitlab.com/simonpunk/susfs4ksu/-/raw/f77334c982f9970958b856665c4d26ddf75e8248/kernel_patches/50_add_susfs_in_gki-android15-6.6.patch
           patch -p1 < 50_add_susfs_in_gki-android15-6.6.patch || true
+
+          cd ..
+          test -f common/include/linux/susfs_def.h || {
+            echo "susfs_def.h not found"; exit 1;
+          }
+          BASE_C=common/fs/proc/base.c
+          grep -q 'susfs_def.h' "$BASE_C" || \
+          sed -i '/#include <linux\/cpufreq_times.h>/a \
+          \
+          #ifdef CONFIG_KSU_SUSFS_SUS_MAP\
+          #include <linux/susfs_def.h>\
+          #endif\
+          ' "$BASE_C"
+          rm -f common/fs/proc/base.c.rej
+          grep -n 'susfs_def.h' "$BASE_C"
           case "${{ github.event.inputs.sub_level }}" in
             6.6.56)
               cd ./fs/proc
@@ -253,12 +268,13 @@ jobs:
           echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
           echo "CONFIG_KSU_MULTI_MANAGER_SUPPORT=y" >> ./common/arch/arm64/configs/gki_defconfig
           printf '%s\n' 'KSU_FULL_NAME_FORMAT="%TAG_NAME%-%COMMIT_SHA%-Re-TG@qdykernel"' >>  ./common/arch/arm64/configs/gki_defconfig
-          # Add VFS configuration settings
+          
           if [ "$ENABLE_B" = "true" ]; then
             echo "CONFIG_KPM=y" >> ./common/arch/arm64/configs/gki_defconfig
           else
             echo "CONFIG_KPM=n" >> ./common/arch/arm64/configs/gki_defconfig
           fi
+          
           echo "CONFIG_CRYPTO_LZ4=y" >> ./common/arch/arm64/configs/gki_defconfig
           echo "CONFIG_CRYPTO_LZ4HC=y" >> ./common/arch/arm64/configs/gki_defconfig
           echo "CONFIG_CRYPTO_LZ4KD=y" >> ./common/arch/arm64/configs/gki_defconfig
